# Generated by Django 4.1.7 on 2023-04-02 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='category',
            field=models.ManyToManyField(to='promptbook.prompt'),
        ),
    ]
