# Generated by Django 4.1.7 on 2023-04-02 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promptbook', '0002_alter_label_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='label',
            name='category',
        ),
        migrations.CreateModel(
            name='PromptLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='promptbook.label')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='promptbook.prompt')),
            ],
        ),
    ]
