# Generated by Django 4.1.7 on 2023-04-04 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promptbook', '0004_alter_prompt_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promptlabel',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='promptbook.prompt'),
        ),
    ]
