# Generated by Django 4.1.7 on 2023-04-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptbook', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='avatars/'),
        ),
    ]
