# Generated by Django 4.1.7 on 2023-04-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptbook', '0008_prompt_is_public_prompt_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='help_text',
            field=models.CharField(default='help text', max_length=255),
            preserve_default=False,
        ),
    ]
