# Generated by Django 4.1.7 on 2023-04-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptbook', '0012_alter_prompt_unique_together_alter_prompt_text_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='flesch_reading_score',
            field=models.FloatField(default=50.0, max_length=6), # 50.0 is a temp default given while migrating
            preserve_default=False,
        ),
    ]
