# Generated by Django 4.2 on 2023-04-10 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promptbook', '0012_alter_prompt_unique_together_alter_prompt_text_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prompt',
            name='labels',
            field=models.ManyToManyField(through='promptbook.PromptLabel', to='promptbook.label'),
        ),
    ]
