# Generated by Django 4.1.7 on 2023-04-24 07:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('promptbook', '0012_alter_prompt_unique_together_alter_prompt_text_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='pinned_by',
            field=models.ManyToManyField(related_name='pinned_categories', to=settings.AUTH_USER_MODEL),
        ),
    ]
