# Generated by Django 4.1.7 on 2023-04-11 14:07

from django.db import migrations
import textstat

def poopulate_reading_score(apps, schema_editor):
    Prompt = apps.get_model('promptbook', 'Prompt')

    for prompt in Prompt.objects.all():
        prompt.flesch_reading_score = textstat.flesch_reading_ease(prompt.text)
        prompt.save()

class Migration(migrations.Migration):

    dependencies = [
        ('promptbook', '0013_prompt_flesch_reading_score'),
    ]

    operations = [
        migrations.RunPython(poopulate_reading_score),
    ]
