# Generated by Django 4.1.7 on 2024-02-19 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("promptbook", "0015_alter_category_name"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="prompt",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="category",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="label",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="promptbook.category",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="prompt",
            name="labels",
            field=models.ManyToManyField(related_name="prompts", to="promptbook.label"),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="promptbook.category"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="prompt",
            unique_together={("text_hash", "category")},
        ),
        migrations.DeleteModel(
            name="PromptLabel",
        ),
        migrations.RemoveField(
            model_name="prompt",
            name="is_public",
        ),
        migrations.RemoveField(
            model_name="prompt",
            name="owner",
        ),
    ]
