# Generated by Django 4.1.7 on 2024-02-19 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promptbook", "0016_alter_prompt_unique_together_category_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
