# Generated by Django 4.1.7 on 2024-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promptbook", "0018_prompt_name_llmmodel_prompt_llm_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="output_format",
            field=models.CharField(
                choices=[("json", "JSON"), ("str", "String")],
                default="str",
                max_length=32,
            ),
        ),
    ]
