# Generated by Django 4.1.7 on 2024-02-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promptbook", "0019_prompt_output_format"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="prompt",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="label",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="llmmodel",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="prompt",
            name="name",
            field=models.CharField(max_length=64),
        ),
        migrations.AddConstraint(
            model_name="label",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="label_unique_name_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="llmmodel",
            constraint=models.UniqueConstraint(
                fields=("category", "name"), name="model_unique_name_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="prompt",
            constraint=models.UniqueConstraint(
                fields=("text_hash", "category"), name="unique_text_hash_category"
            ),
        ),
        migrations.AddConstraint(
            model_name="prompt",
            constraint=models.UniqueConstraint(
                fields=("name", "category"), name="prompt_unique_name_category"
            ),
        ),
    ]
