# Generated by Django 4.1.7 on 2024-02-22 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promptbook", "0020_alter_prompt_unique_together_alter_label_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="help_text",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=255,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Code must be start with a lowercase letter and contain only lowercase letters, numbers, and underscores.",
                        regex="^[a-z][a-z0-9_]*$",
                    )
                ],
            ),
        ),
    ]
