# Generated by Django 4.1.7 on 2024-02-22 09:09

import django.core.validators
from django.db import migrations, models


def generate_display_name(apps, schema_editor):
    Category = apps.get_model('promptbook', 'Category')
    for c in Category.objects.all():
        if not c.display_name:
            c.display_name = c.name
            c.save(update_fields=['display_name'])



class Migration(migrations.Migration):
    dependencies = [
        ("promptbook", "0021_alter_category_help_text_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="help_text",
        ),
        migrations.AddField(
            model_name="category",
            name="display_name",
            field=models.CharField(
                max_length=64,
            ),
        ),
        migrations.RunPython(
            generate_display_name,
            reverse_code=migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Must be start with a lowercase letter and contain only lowercase letters, numbers, and underscores.",
                        regex="^[a-z][a-z0-9_]*$",
                    )
                ],
            ),
        ),
    ]
