# Generated by Django 4.1.7 on 2024-02-24 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promptbook", "0022_remove_category_help_text_category_display_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="prompt",
            name="last_used_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
